version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/dusk
    versions:
    - 6.11.0
    - 6.11.2
  - dependency-name: spatie/data-transfer-object
    versions:
    - 2.6.0
    - 2.8.0
  - dependency-name: laravel/framework
    versions:
    - 6.20.11
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.13
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.18
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: "@popperjs/core"
    versions:
    - 2.6.0
  - dependency-name: vuex
    versions:
    - 3.6.0
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
